# Generated by Django 4.0.5 on 2022-12-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_pieinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieinfo',
            name='name',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
